import type { Lang } from "./site-data";

export const COPY = {
  es: {
    menu: "Menú", close: "Cerrar", introducing: "Presentamos", by: "Por",
    navCollections: "Colecciones", navInterior: "Interiorismo", navDesigners: "Diseñadores", navHouse: "La Casa", navJournal: "Journal",
    quote: "Cotización", tagline: "Casa de diseño y curaduría de interiores",
    heroA: "Un lujo culto, íntimo y silencioso", explore: "Explorar colecciones", viewRoom: "Ver ambiente", viewProjects: "Ver proyectos", viewAll: "Ver todo",
    statement: "Piezas excepcionales, talento internacional y una mirada estética atemporal para crear espacios con identidad.",
    statementShort: "Casa Kruyff reúne piezas de diseñadores de todo el mundo y las integra en espacios sofisticados, personales y atemporales.",
    heroB1: "El legado clásico,", heroB2: "en diálogo con lo contemporáneo.",
    quoteLine: "Objetos capaces de conservar su belleza más allá de las tendencias.",
    heroC: "Más que una tienda de decoración.",
    valueProp: "Un universo completo de diseño: piezas, curaduría, interiorismo y desarrollo de conceptos.",
    newPieces: "Piezas recientes", appointment: "Agendar cita privada",
    interiorTitle: "Espacios que reflejan a quien los habita",
    interiorBody: "Desarrollamos conceptos de interiorismo que combinan diseño, calidad y permanencia. Cuidamos cada detalle, desde la selección hasta la instalación.",
    designersIntro: "Valoramos el diseño con identidad, historia y autoría. Estos son algunos de los estudios y autores que forman parte de la curaduría.",
    casaLead: "Donde el legado clásico se encuentra con el diseño contemporáneo",
    casaBody: "Casa Kruyff es una casa de diseño y curaduría de interiores que reúne piezas excepcionales, talento internacional y una mirada estética atemporal para crear espacios con identidad. Su propuesta no persigue tendencias pasajeras: selecciona objetos, materiales y conceptos capaces de conservar su belleza, relevancia y valor con el paso del tiempo.",
    values: "Valores", read: "Leer",
    contactTitle: "Visítenos en privado", contactBody: "Recibimos con cita en Lomas de Chapultepec. Cuéntenos sobre su espacio y le acompañaremos en la selección.",
    quoteList: "Piezas en su solicitud", remove: "Quitar", fName: "Nombre", fEmail: "Correo", fPhone: "Teléfono", fProfile: "Perfil", fMsg: "Sobre su proyecto", send: "Enviar solicitud",
    thanks: "Gracias. Le escribiremos en breve para acordar su visita.",
    quoteNote: "El precio y la disponibilidad se confirman de forma personal.", add: "Añadir a cotización", added: "En su cotización",
    visit: "Visitas", location: "Lomas de Chapultepec, Ciudad de México", byAppt: "Solo con cita", follow: "Seguir", all: "Todo",
    specs: ["Materiales", "Dimensiones", "Procedencia", "Entrega"],
    profiles: ["Cliente residencial", "Coleccionista de diseño", "Interiorista o arquitecto", "Proyecto de hospitalidad"],
    pieceDesc: "Pieza seleccionada por su diseño, calidad y procedencia. Su forma y sus materiales están pensados para permanecer.",
    leadTime: "8 a 12 semanas",
    steps: [
      ["Escucha", "Conocemos a quien habitará el espacio: su rutina, su historia y lo que desea sentir."],
      ["Concepto", "Desarrollamos una propuesta de materiales, atmósfera y distribución."],
      ["Curaduría", "Seleccionamos piezas de autores de todo el mundo, o las comisionamos a medida."],
      ["Instalación", "Acompañamos la entrega y colocación de cada pieza hasta el último detalle."],
    ] as [string, string][],
    pillars: [
      ["Visión", "Ser una casa de diseño referente por su curaduría internacional, su estética atemporal y su manera de crear espacios con identidad."],
      ["Misión", "Seleccionar piezas excepcionales y desarrollar conceptos de interiorismo que combinen diseño, calidad y permanencia."],
      ["Propuesta", "Más que una tienda de decoración, ofrece un universo completo de diseño: piezas, curaduría, interiorismo y desarrollo de conceptos."],
    ] as [string, string][],
    valuesList: [
      ["Curaduría", "Cada pieza es seleccionada por su diseño, calidad y procedencia."],
      ["Atemporalidad", "Elegimos objetos capaces de conservar su belleza más allá de las tendencias."],
      ["Excelencia", "Cuidamos cada detalle, desde la selección hasta la instalación."],
      ["Autenticidad", "Valoramos el diseño con identidad, historia y autoría."],
      ["Individualidad", "Cada espacio debe reflejar a quien lo habita."],
      ["Discreción", "Comunicamos exclusividad con sutileza, evitando la ostentación."],
    ] as [string, string][],
    feature: { tag: "Materiales", title: "El travertino y la paciencia del tiempo", dek: "Una piedra que se forma durante siglos y que, en un interior, gana carácter con cada año." },
    articles: [
      ["a1", "Diseñadores", "Una tarde en el taller de Taller Ocre"],
      ["a2", "Interiorismo", "Cómo componer una sala alrededor de una sola pieza"],
      ["a3", "Procedencia", "El tapete anudado a mano, nudo por nudo"],
    ] as [string, string, string][],
  },
  en: {
    menu: "Menu", close: "Close", introducing: "Introducing", by: "By",
    navCollections: "Collections", navInterior: "Interiors", navDesigners: "Designers", navHouse: "The House", navJournal: "Journal",
    quote: "Quote", tagline: "A house of design and interior curation",
    heroA: "A cultured, intimate and quiet luxury", explore: "Explore collections", viewRoom: "View room", viewProjects: "View projects", viewAll: "View all",
    statement: "Exceptional pieces, international talent and a timeless aesthetic vision to create spaces with identity.",
    statementShort: "Casa Kruyff brings together pieces by designers from around the world and places them in sophisticated, personal and timeless spaces.",
    heroB1: "Classical legacy,", heroB2: "in dialogue with the contemporary.",
    quoteLine: "Objects that keep their beauty beyond trends.",
    heroC: "More than a decoration store.",
    valueProp: "A complete universe of design: pieces, curation, interiors and concept development.",
    newPieces: "Recent pieces", appointment: "Book a private visit",
    interiorTitle: "Spaces that reflect those who live in them",
    interiorBody: "We develop interior concepts that combine design, quality and permanence. We attend to every detail, from selection to installation.",
    designersIntro: "We value design with identity, history and authorship. These are some of the studios and authors in our curation.",
    casaLead: "Where classical legacy meets contemporary design",
    casaBody: "Casa Kruyff is a house of design and interior curation that brings together exceptional pieces, international talent and a timeless aesthetic vision to create spaces with identity. It does not chase passing trends: it selects objects, materials and concepts able to keep their beauty, relevance and value over time.",
    values: "Values", read: "Read",
    contactTitle: "Visit us privately", contactBody: "We receive by appointment in Lomas de Chapultepec. Tell us about your space and we will guide you through the selection.",
    quoteList: "Pieces in your request", remove: "Remove", fName: "Name", fEmail: "Email", fPhone: "Phone", fProfile: "Profile", fMsg: "About your project", send: "Send request",
    thanks: "Thank you. We will write shortly to arrange your visit.",
    quoteNote: "Price and availability are confirmed personally.", add: "Add to quote", added: "In your quote",
    visit: "Visits", location: "Lomas de Chapultepec, Mexico City", byAppt: "By appointment only", follow: "Follow", all: "All",
    specs: ["Materials", "Dimensions", "Provenance", "Lead time"],
    profiles: ["Residential client", "Design collector", "Interior designer or architect", "Hospitality project"],
    pieceDesc: "A piece selected for its design, quality and provenance. Its form and materials are made to endure.",
    leadTime: "8 to 12 weeks",
    steps: [
      ["Listening", "We get to know who will live in the space: their routine, their history and what they want to feel."],
      ["Concept", "We develop a proposal of materials, atmosphere and layout."],
      ["Curation", "We select pieces by authors from around the world, or commission them to measure."],
      ["Installation", "We oversee the delivery and placement of each piece down to the last detail."],
    ] as [string, string][],
    pillars: [
      ["Vision", "To be a reference house of design for its international curation, its timeless aesthetic and its way of creating spaces with identity."],
      ["Mission", "To select exceptional pieces and develop interior concepts that combine design, quality and permanence."],
      ["Proposition", "More than a decoration store, a complete universe of design: pieces, curation, interiors and concept development."],
    ] as [string, string][],
    valuesList: [
      ["Curation", "Every piece is selected for its design, quality and provenance."],
      ["Timelessness", "We choose objects that keep their beauty beyond trends."],
      ["Excellence", "We attend to every detail, from selection to installation."],
      ["Authenticity", "We value design with identity, history and authorship."],
      ["Individuality", "Every space should reflect the person who lives in it."],
      ["Discretion", "We convey exclusivity with subtlety, avoiding ostentation."],
    ] as [string, string][],
    feature: { tag: "Materials", title: "Travertine and the patience of time", dek: "A stone formed over centuries that, in an interior, gains character with every year." },
    articles: [
      ["a1", "Designers", "An afternoon at Taller Ocre"],
      ["a2", "Interiors", "Composing a living room around a single piece"],
      ["a3", "Provenance", "The hand-knotted rug, knot by knot"],
    ] as [string, string, string][],
  },
} satisfies Record<Lang, unknown>;

export type Copy = typeof COPY["es"];
